language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
# command to run tests
script:
  - pytest