# This workflows will upload a Python Package using Poetry when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:

  Upload:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Test
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          source $HOME/.poetry/env
          export POETRY_PYPI_TOKEN_PYPI=$PYPI_TOKEN

          poetry config pypi-token.testpypi $PYPI_TOKEN
          poetry config http-basic.testpypi "__token__" "${PYPI_TOKEN}"
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --build -r testpypi

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source $HOME/.poetry/env
          export POETRY_PYPI_TOKEN_PYPI=$PYPI_TOKEN

          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry config http-basic.pypi "__token__" "${PYPI_TOKEN}"
          poetry publish --build

       - name: Publish distribution 📦 to PyPI
         if: startsWith(github.ref, 'refs/tags')
         uses: pypa/gh-action-pypi-publish@master
         with:
           password: ${{ secrets.PYPI_API_TOKEN }}